# -*- coding: utf-8 -*-
"""selection_sort

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wc1GU9vh7Y06JgPKuZORTcstCOs2lyPM
"""

SelectionSortStyle(A, n):
    B = A
    i = 0
    while i < n:
        minIndex = i
        for j = i+1 to n-1:
            if B[j] < B[minIndex]:
                minIndex = j
        swap B[i] and B[minIndex]
        i = i + 1
    return B